#
# Please do not edit this file until you have read the
# site policy file for dot-files: /etc/home/README
 
if (-r /etc/home/cshrc) source /etc/home/cshrc

umask 27
source $HOME/.myenv/init/csh.csh

#bindkey ^p i-search-back
#bindkey ^n i-search-fwd
