#!/bin/sh
#
# Simple Redis init.d script conceived to work on Linux systems
# as it does use of the /proc filesystem.

REDISPORT=6379
EXEC=/data/services/redis-2.6.3/src/redis-server
CLIEXEC=/data/services/redis-2.6.3/src/redis-cli

PIDFILE=/var/run/redis_${REDISPORT}.pid
CONF="/data/redis/conf/redis_${REDISPORT}.conf"

[ ! -e $EXEC ] && echo "ERROR: $EXEC not exist!" && exit 1
[ ! -e $CONF ] && echo "ERROR: $CONF not exist!" && exit 1

case "$1" in
    start)
        if [ -f $PIDFILE ]
        then
                echo "$PIDFILE exists, process is already running or crashed"
        else
                echo "Starting Redis server..."
                $EXEC $CONF
        fi
        ;;
    stop)
        if [ ! -f $PIDFILE ]
        then
                echo "$PIDFILE does not exist, process is not running"
        else
                PID=$(cat $PIDFILE)
                echo "Stopping ..."
                $CLIEXEC -p $REDISPORT shutdown
                while [ -x /proc/${PID} ]
                do
                    echo "Waiting for Redis to shutdown ..."
                    sleep 1
                done
                echo "Redis stopped"
        fi
        ;;
    *)
        echo "Please use start or stop as first argument"
        ;;
esac
